config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root "homes#top"
get "/about" => "homes#about"

namespace :public do
	resources :customers, only: [:show, :update, :edit]
	resources :cart_items, only: [:index, :create, :update, :destroy]
	resources :items, only: [:index, :show]
	resources :orders, only: [:new, :create, :index, :show]
	resources :shipppings
end

namespace :admin do
	resources :customers, only: [:index, :show, :edit, :update]
	resources :genres, only: [:index, :create, :edit, :update]
	resources :items
	resources :orders
end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :address, presence: true
  validates :last_name_kanji, presence: true
  validates :first_name_kanji, presence: true
  validates :postal_code, presence: true
  validates :tel, presence: true

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :shippings, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
	validates :name, presence: true
	validates :price, presence: true

	belongs_to :genre, optional: true
	has_many :cart_items, dependent: :destroy

	attachment :image

	enum sales_status:{
		売り切れ: false,
		販売中: true
	}, _suffix: true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
end

app/models/shipping.rb
class Shipping < ApplicationRecord
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
	def index
		@items = Item.all
	end

	def new
		@item = Item.new
	end

	def create
		@item = Item.new(item_params)
		@items = Item.all
        if @item.save
          redirect_to admin_items_path
        else
        redirect_back(fallback_location: admin_items_path)
        end
	end

	def show
		@item = Item.find(params[:id])
	end

	def edit
		@item = Item.find(params[:id])
	end

	def update
		@item = Item.find(params[:id])
		@items = Item.all
        if @item.update(item_params)
          redirect_to admin_items_path(@item)
        else
        redirect_back(fallback_location: admin_items_path)
        end
	end

	private
    def item_params
    params.require(:item).permit(:name, :price, :image, :introduction, :sales_status, :genre_id)
    end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
	def index
		@genre = Genre.new
		@genres = Genre.where(valid_status: true)
	end
  
	def edit
		@genre = Genre.find(params[:id])
	end

	def create
		@genre = Genre.new(genre_params)
		@genres = Genre.all
		if @genre.save
		   redirect_back(fallback_location: root_path)
		else
		   render :index
		end
	end
  
	def update
		@genre = Genre.find(params[:id])
		if @genre.update(genre_params)
		   redirect_to admin_genres_path
		else
		   redirect_back(fallback_location: root_path)
		end
	end

	private
    def genre_params
    	params.require(:genre).permit(:name, :valid_status)
    end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
	def index
		@items = Item.all
	end

	def new
		@item = Item.new
	end

	def create
		@item = Item.new(item_params)
		@items = Item.all
		if @item.save
			redirect_to admin_items_path
		else
			redirect_back(fallback_location: admin_items_path)
		end
	end

	def show
		@item = Item.find(params[:id])
	end

	def edit
		@item = Item.find(params[:id])
	end

	def update
		@item = Item.find(params[:id])
		@items = Item.all
		if @item.update(item_params)
			redirect_to admin_items_path(@item)
		else
			redirect_back(fallback_location: admin_items_path)
		end
	end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
	def index
		@orders = Order.page(params[:page]).reverse_order
	end
	def show
	    @order = Order.find(params[:id])
	    @order_items = @order.order_items.all
	end
	def update
	    @order = Order.find(params[:id])
        if @order.update(order_params)
           redirect_to admin_order_path(@order)
        else
        render "show"
        end
	end

	private
    def order_params
    params.require(:order).permit(:status)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<div>
	<div>
		<p><%= @customer.last_name_kanji %><%= @customer.first_name_kanji %>さんの会員情報編集ページ</p>
		<div>

			<%= form_for [:admin, @customer] do |f| %>

			<div>
				<div>顧客ID</div>
				<div>氏名</div>
				<div>フリガナ</div>
				<div>郵便番号</div>
				<div>住所</div>
				<div>電話番号</div>
				<div>メールアドレス</div>
				<div>
					<%= link_to "編集する", edit_admin_customer_path(@customer) %>
				</div>
				<div>
					<%= f.submit "変更を保存する" %>
				</div>
			</div>
			<div>
				<div>
					<%= customer.id %>
				</div>
				<div>
					<%= @customer.last_name_kanji %>&emsp;<%= @customer.first_name_kanji %>
				</div>
				<div>
					<%= @customer.last_name_kana %>&emsp;<%= @customer.first_name_kana %>
				</div>
				<div>
					<%= @customer.postal_code %>
				</div>
				<div>
					<%= @customer.address %>
				</div>
				<div>
					<%= @customer.tel %>
				</div>
				<div>
					<%= @customer.email %>
				</div>
			</div>

			<% end %>

		</div>
	</div>
</div>

app/views/admin/customers/index.html.erb
<div>
	<div>
		<p>会員一覧</p>
		<table>
			<thead>
				<tr>
					<th>会員ID</th>
					<th>氏名</th>
					<th>メールアドレス</th>
					<th>ステータス</th>
				</tr>
			</thead>
			<tbody>
				<% @customers.each do |customer| %>
				<tr>
					<td>
						<%= customer.id %>
					</td>
					<td>
						<%= link_to admin_customer_path(customer) do %>
						<%= customer.last_name_kanji %><%= customer.first_name_kanji %>
						<% end %>
					</td>
					<td>
						<%= customer.email %>
					</td>
					<td>
						<%= customer.is_deleted %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/admin/customers/show.html.erb
<div>
	<div>
		<p><%= @customer.last_name_kanji %><%= @customer.first_name_kanji %>さんの会員詳細</p>
		<div>
			<div>
				<div>顧客ID</div>
				<div>氏名</div>
				<div>フリガナ</div>
				<div>郵便番号</div>
				<div>住所</div>
				<div>電話番号</div>
				<div>メールアドレス</div>
				<div>
					<%= link_to "編集する", edit_admin_customer_path(@customer) %>
				</div>
			</div>
			<div>
				<div>
					<%= customer.id %>
				</div>
				<div>
					<%= @customer.last_name_kanji %>&emsp;<%= @customer.first_name_kanji %>
				</div>
				<div>
					<%= @customer.last_name_kana %>&emsp;<%= @customer.first_name_kana %>
				</div>
				<div>
					<%= @customer.postal_code %>
				</div>
				<div>
					<%= @customer.address %>
				</div>
				<div>
					<%= @customer.tel %>
				</div>
				<div>
					<%= @customer.email %>
				</div>
			</div>
		</div>
	</div>
</div>