config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root "homes#top"
get "/about" => "homes#about"

namespace :public do
	resources :customers, only: [:show, :update, :edit]
	resources :cart_items, only: [:index, :create, :update, :destroy]
	resources :items, only: [:index, :show]
	resources :orders, only: [:new, :create, :index, :show]
	resources :shipppings
end

namespace :admin do
	resources :customers, only: [:index, :show, :edit, :update]
	resources :genres, only: [:index, :create, :edit, :update]
	resources :items
	resources :orders
end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :address, presence: true
  validates :last_name_kanji, presence: true
  validates :first_name_kanji, presence: true
  validates :postal_code, presence: true
  validates :tel, presence: true

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :shippings, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
	validates :name, presence: true
	validates :price, presence: true

	belongs_to :genre, optional: true
	has_many :cart_items, dependent: :destroy

	attachment :image

	enum sales_status:{
		売り切れ: false,
		販売中: true
	}, _suffix: true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
end

app/models/shipping.rb
class Shipping < ApplicationRecord
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
	def index
		@genre = Genre.new
		@genres = Genre.where(valid_status: true)
	end
  
	def edit
		@genre = Genre.find(params[:id])
	end

	def create
		@genre = Genre.new(genre_params)
		@genres = Genre.all
		if @genre.save
		   redirect_back(fallback_location: root_path)
		else
		   render :index
		end
	end
  
	def update
		@genre = Genre.find(params[:id])
		if @genre.update(genre_params)
		   redirect_to admin_genres_path
		else
		   redirect_back(fallback_location: root_path)
		end
	end

	private
    def genre_params
    	params.require(:genre).permit(:name, :valid_status)
    end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
	def index
		@items = Item.all
	end

	def new
		@item = Item.new
	end

	def create
		@item = Item.new(item_params)
		@items = Item.all
		if @item.save
			redirect_to admin_items_path
		else
			redirect_back(fallback_location: admin_items_path)
		end
	end

	def show
		@item = Item.find(params[:id])
	end

	def edit
		@item = Item.find(params[:id])
	end

	def update
		@item = Item.find(params[:id])
		@items = Item.all
		if @item.update(item_params)
			redirect_to admin_items_path(@item)
		else
			redirect_back(fallback_location: admin_items_path)
		end
	end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
	def index
		@orders = Order.page(params[:page]).reverse_order
	end
	def show
	    @order = Order.find(params[:id])
	    @order_items = @order.order_items.all
	end
	def update
	    @order = Order.find(params[:id])
        if @order.update(order_params)
           redirect_to admin_order_path(@order)
        else
        render "show"
        end
	end

	private
    def order_params
    params.require(:order).permit(:status)
    end
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
<div>
	<div>
		<p>ジャンル編集</p>
		<div>
			<%= form_for @genre, :url => {:action => :update} do |f| %>
			<div>
				<label>ジャンル</label>
			</div>
			<div>
				<%= f.text_field :name %>
			</div>
			<div>
				<label>
					<%= f.radio_button :valid_status, 1 %>有効
				</label>
				<label>
					<%= f.radio_button :valid_status, 0 %>無効
				</label>
			</div>
			<div>
				<%= f.submit '変更を保存する' %>
			</div>
		</div>
	</div>
</div>

app/views/admin/genres/index.html.erb
<div>
	<div>
		<p>ジャンル一覧・追加</p>
		<div>
			<%= form_for(@genre, url: admin_genres_path) do |f| %>
			<div>
				<label>ジャンル</label>
			</div>
			<div>
				<%= f.text_field :name %>
			</div>
			<div>
				<%= f.radio_button :valid_status, :true %>
				<%= f.label :valid_status, "有効" %>
				<%= f.radio_button :valid_status, :false %>
				<%= f.label :valid_status, "無効" %>
			</div>
			<div>
				<%= f.submit '追加'　%>
			</div>
			<% end %>
		</div>
	</div>
	<div>
		<div>
			<table>
				<thead>
					<tr>
						<th>ジャンル</th>
						<th>状態</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @genres.each do |genre| %>
					<tr>
						<td>
							<%= genre.name %>
						</td>
						<td>
							<% if genre.valid_status == true %>
								有効
							<% else %>
								無効
							<% end %>
						</td>
						<td>
							<%= link_to "編集", edit_admin_genre_path(genre) %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/admin/items/edit.html.erb
<div>
	<p>商品編集</p>
	<div>
		<%= form_for @item, :url => {:action => :update} do |f| %>
		<div>
			<div>
				<div>
					<%= attachment_image_tag @item, :image, fallback: "img/no_image.jpg", size:"300x200" %>
				</div>
				<%= f.attachment_field :image %>
			</div>
		</div>
		<div>
			<div>
				<label>商品名</label>
				<div><%= f.text_field :name %></div>
			</div>
			<div>
				<label>商品説明</label>
				<div><%= f.text_area :introduction %></div>
			</div>
			<div>
				<label>ジャンル</label>
				<div><!--<%= f.text_field :name %>--></div>
			</div>
			<div>
				<label>税抜価格</label>
				<div><%= f.number_field :price %>円</div>
			</div>
			<div>
				<label>販売ステータス</label>
				<div><%= f.select :sales_status, Item.sales_status.keys.to_a %></div>
			</div>
		</div>
		<div>
			<%= f.submit '変更を保存' %>
		</div>
		<% end %>
	</div>
</div>

app/views/admin/items/index.html.erb
<div>
	<p>商品一覧</p>
	<div></div>
	<div>
		<table>
			<thead>
				<tr>
					<th>商品ID</th>
					<th>商品名</th>
					<th>税抜価格</th>
					<th>ジャンル</th>
					<th>ステータス</th>
				</tr>
			</thead>
			<tbody>
				<% @items.each do |item| %>
				<tr>
					<td>
						<%= item.id %>
					</td>
					<td>
						<%= item.name %>
					</td>
					<td>
						<%= item.price %>
					</td>
					<td>
						<%= item.genre.name %>
					</td>
					<td>
						<%= item.sales_status %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/admin/items/new.html.erb
<div>
	<p>商品新規登録</p>
	<div>
		<div>
			<%= form_for @item, :url => {:action => :create} do |f| %>
				<div>
					<%= attachment_image_tag @item, :image, fallback: "img/no_image.jpg", size:"300x200" %>
					<%= f.attachment_field :image %>
				</div>
				<div>
					<div>
						<label>商品名</label>
						<div>
							<%= f.text_field :name %>
						</div>
					</div>
				</div>
				<div>
					<div>
						<label>商品説明</label>
						<div>
							<%= f.text_area :introduction %>
						</div>
					</div>
				</div>
				<div>
					<div>
						<label>ジャンル</label>
						<div>
							<!--<%= f.collection_select %>-->
						</div>
					</div>
				</div>
				<div>
					<div>
						<label>税抜価格</label>
						<div>
							<%= f.number_field :price %>円
						</div>
					</div>
				</div>
				<div>
					<div>
						<label>販売<br>ステータス</label>
						<div>
							<%= f.select :sales_status, Item.sales_statuses.keys.to_a %>
						</div>
					</div>
				</div>
				<div>
					<%= f.submit '新規登録' %>
				</div>
		</div>
	</div>
</div>

app/views/admin/items/show.html.erb
<div>
	<div>
		<p>商品詳細</p>
		<div>
			<%= attachment_image_tag @item, :image, fallback: 'img/no_image.jpg', size:'300x300' %>
		</div>
		<div>
			<div>
				<label>商品名</label>
				<div><%= @item.name %></div>
			</div>
			<div>
				<label>商品説明</label>
				<div><%= @item.introduction %></div>
			</div>
			<div>
				<label>ジャンル</label>
				<div><%= @item.genre.name %></div>
			</div>
			<div>
				<label>税込価格(税抜価格)</label>
				<div>
					<%= (@item.price.to_i*1.10).floor %>
					(<%= @item.price %>)円
				</div>
			</div>
			<div>
				<label>販売ステータス</label>
				<div><%= @item.sales_status %></div>
			</div>
			<div><%= link_to "編集する", edit_admin_item_path %></div>
		</div>
	</div>
</div>

app/views/admin/orders/index.html.erb
<div>
	<div>
		<p>注文履歴一覧</p>
		<table>
			<thead>
				<tr>
					<th>購入日時</th>
					<th>購入者</th>
					<th>注文個数</th>
					<th>注文ステータス</th>
				</tr>
			</thead>
			<tbody>
				<% @orders.each do |f| %>
				<tr>
					<td>
						<%= link_to admin_order_path(order) do %>
						<%= order.created_at.strftime("%Y-%m-%d %H:%M") %>
						<% end %>
					</td>
					<td>
						<%= order.customer.last_name_kanji %>
						<%= order.customer.first_name_kanji %>
					</td>
					<td>
						<%= order.order_items.sum(:amount) %>
					</td>
					<td>
						<%= order.status %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>